<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SekolahSeeder extends Seeder
{
    public function run()
    {
        // Data sekolah untuk Kabupaten Tanah Datar, Sumatera Barat
        $sekolah = [
            // ==================== SD (20 data) ====================
            [
                'nama_sekolah' => 'SD Negeri 01 Batusangkar',
                'npsn' => '10100001',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Soekarno Hatta No. 1, Batusangkar',
                'latitude' => -0.45678910,
                'longitude' => 100.58901234,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Ahmad Fauzi, M.Pd.',
                'kontak' => '081234567801',
                'tahun_berdiri' => 1950,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://sdn01batusangkar.sch.id',
                'deskripsi_sekolah' => 'SD Negeri 01 Batusangkar merupakan sekolah dasar tertua di Kecamatan Batusangkar dengan prestasi akademik dan non-akademik yang gemilang.',
                'visi' => 'Terwujudnya peserta didik yang beriman, berilmu, berkarakter, dan berwawasan lingkungan.',
                'misi' => 'Menyelenggarakan pembelajaran aktif, kreatif, dan menyenangkan; Membangun karakter religius dan nasionalis; Mengembangkan potensi siswa secara optimal.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Batusangkar',
                'npsn' => '10100002',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Diponegoro No. 15, Batusangkar',
                'latitude' => -0.45987654,
                'longitude' => 100.59234567,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Dra. Siti Rahmah, M.Si.',
                'kontak' => '081234567802',
                'tahun_berdiri' => 1955,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://sdn02batusangkar.sch.id',
                'deskripsi_sekolah' => 'SD Negeri 02 Batusangkar dikenal dengan program adiwiyata dan lingkungan sekolah yang hijau dan asri.',
                'visi' => 'Unggul dalam prestasi, berbudaya lingkungan, dan berakhlak mulia.',
                'misi' => 'Meningkatkan mutu pembelajaran; Menanamkan cinta lingkungan; Membudayakan perilaku hidup bersih dan sehat.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 03 Batusangkar',
                'npsn' => '10100003',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Pahlawan No. 8, Batusangkar',
                'latitude' => -0.46234567,
                'longitude' => 100.59567890,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Zulkifli, S.Pd., M.M.',
                'kontak' => '081234567803',
                'tahun_berdiri' => 1960,
                'kurikulum' => 'Kurikulum 2013',
                'website' => 'https://sdn03batusangkar.sch.id',
                'deskripsi_sekolah' => 'SD Negeri 03 Batusangkar memiliki program unggulan tahfidz dan seni budaya Minangkabau.',
                'visi' => 'Mencetak generasi cerdas, kreatif, dan berkarakter Pancasila.',
                'misi' => 'Mengoptimalkan proses pembelajaran; Mengembangkan bakat dan minat siswa; Menanamkan nilai-nilai budaya lokal.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 04 Batusangkar',
                'npsn' => '10100004',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Merdeka No. 22, Batusangkar',
                'latitude' => -0.46543210,
                'longitude' => 100.59876543,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Yusra Dewi, S.Pd.',
                'kontak' => '081234567804',
                'tahun_berdiri' => 1965,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 04 Batusangkar terus berbenah meningkatkan kualitas pendidikan dan sarana prasarana.',
                'visi' => 'Berprestasi, beriman, dan berbudaya.',
                'misi' => 'Melaksanakan pembelajaran efektif; Meningkatkan profesionalisme guru; Membangun kerjasama dengan orang tua dan masyarakat.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 05 Batusangkar',
                'npsn' => '10100005',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Imam Bonjol No. 5, Batusangkar',
                'latitude' => -0.46890123,
                'longitude' => 100.60123456,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Marzuki, M.Pd.',
                'kontak' => '081234567805',
                'tahun_berdiri' => 1970,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://sdn05batusangkar.sch.id',
                'deskripsi_sekolah' => 'SD Negeri 05 Batusangkar memiliki laboratorium komputer dan perpustakaan digital yang lengkap.',
                'visi' => 'Terwujudnya sekolah unggul berbasis teknologi dan iman taqwa.',
                'misi' => 'Mengintegrasikan teknologi dalam pembelajaran; Meningkatkan literasi digital; Membentuk karakter siswa yang berakhlak mulia.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Sungai Tarab',
                'npsn' => '10100006',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Sungai Tarab No. 10, Sungai Tarab',
                'latitude' => -0.42000000,
                'longitude' => 100.56000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Nurhayati, S.Pd., M.Pd.',
                'kontak' => '081234567806',
                'tahun_berdiri' => 1958,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 01 Sungai Tarab merupakan sekolah favorit di Kecamatan Sungai Tarab dengan berbagai prestasi.',
                'visi' => 'Unggul dalam mutu, berakar pada budaya, dan berwawasan global.',
                'misi' => 'Meningkatkan kualitas pembelajaran; Melestarikan budaya Minangkabau; Mengembangkan kemampuan global siswa.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Sungai Tarab',
                'npsn' => '10100007',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Pendidikan No. 3, Sungai Tarab',
                'latitude' => -0.42345678,
                'longitude' => 100.56345678,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Ermawati, S.Pd.',
                'kontak' => '081234567807',
                'tahun_berdiri' => 1962,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 02 Sungai Tarab melayani pendidikan dasar bagi masyarakat di wilayah Sungai Tarab bagian timur.',
                'visi' => 'Cerdas, terampil, dan berakhlak mulia.',
                'misi' => 'Menyelenggarakan pendidikan berkualitas; Mengembangkan keterampilan siswa; Membudayakan nilai-nilai keagamaan.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Lima Kaum',
                'npsn' => '10100008',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Lima Kaum No. 7, Lima Kaum',
                'latitude' => -0.48000000,
                'longitude' => 100.61000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Asrul, M.Pd.',
                'kontak' => '081234567808',
                'tahun_berdiri' => 1953,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://sdn01limakaum.sch.id',
                'deskripsi_sekolah' => 'SD Negeri 01 Lima Kaum memiliki sejarah panjang dalam dunia pendidikan di Kabupaten Tanah Datar.',
                'visi' => 'Terwujudnya generasi emas yang berilmu, beriman, dan berdaya saing.',
                'misi' => 'Meningkatkan mutu akademik; Membina mental spiritual; Mengembangkan potensi siswa secara holistik.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Lima Kaum',
                'npsn' => '10100009',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Datuak Bandaro No. 12, Lima Kaum',
                'latitude' => -0.48345678,
                'longitude' => 100.61345678,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Rusmiati, S.Pd.',
                'kontak' => '081234567809',
                'tahun_berdiri' => 1968,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 02 Lima Kaum berkomitmen memberikan layanan pendidikan terbaik bagi masyarakat.',
                'visi' => 'Berprestasi, berkarakter, dan berbudaya lingkungan.',
                'misi' => 'Meningkatkan prestasi akademik dan non-akademik; Membentuk karakter siswa; Menanamkan kepedulian lingkungan.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Tanjung Emas',
                'npsn' => '10100010',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Tanjung Emas No. 5, Tanjung Emas',
                'latitude' => -0.44000000,
                'longitude' => 100.58000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Syafruddin, M.Pd.',
                'kontak' => '081234567810',
                'tahun_berdiri' => 1956,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://sdn01tanjungemas.sch.id',
                'deskripsi_sekolah' => 'SD Negeri 01 Tanjung Emas dikenal dengan program literasi dan numerasi yang kuat.',
                'visi' => 'Mewujudkan siswa cerdas, kreatif, dan berakhlak karimah.',
                'misi' => 'Mengembangkan budaya literasi; Meningkatkan kompetensi numerasi; Membina akhlak mulia siswa.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Tanjung Emas',
                'npsn' => '10100011',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. M. Yamin No. 20, Tanjung Emas',
                'latitude' => -0.44345678,
                'longitude' => 100.58345678,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Yulismar, S.Pd.',
                'kontak' => '081234567811',
                'tahun_berdiri' => 1972,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 02 Tanjung Emas terus berupaya meningkatkan mutu pendidikan dan pelayanan.',
                'visi' => 'Sekolah berkualitas, siswa berprestasi, dan berbudaya.',
                'misi' => 'Meningkatkan kualitas pembelajaran; Mengembangkan bakat siswa; Membudayakan gotong royong.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Padang Ganting',
                'npsn' => '10100012',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Padang Ganting No. 1, Padang Ganting',
                'latitude' => -0.50000000,
                'longitude' => 100.64000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Zainuddin, M.Pd.',
                'kontak' => '081234567812',
                'tahun_berdiri' => 1960,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 01 Padang Ganting melayani pendidikan di wilayah Kecamatan Padang Ganting.',
                'visi' => 'Terwujudnya siswa yang berprestasi, beriman, dan berwawasan lingkungan.',
                'misi' => 'Menyelenggarakan pembelajaran berkualitas; Membina keimanan dan ketaqwaan; Menanamkan cinta lingkungan.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Padang Ganting',
                'npsn' => '10100013',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Syekh Burhanuddin No. 8, Padang Ganting',
                'latitude' => -0.50345678,
                'longitude' => 100.64345678,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Eliyanti, S.Pd.',
                'kontak' => '081234567813',
                'tahun_berdiri' => 1975,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 02 Padang Ganting berkomitmen mencerdaskan kehidupan bangsa melalui pendidikan berkualitas.',
                'visi' => 'Cerdas, terampil, beriman, dan berbudaya.',
                'misi' => 'Meningkatkan mutu pendidikan; Mengembangkan keterampilan hidup; Membina akhlak mulia.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Rambatan',
                'npsn' => '10100014',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Rambatan No. 3, Rambatan',
                'latitude' => -0.52000000,
                'longitude' => 100.66000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Masri, M.Pd.',
                'kontak' => '081234567814',
                'tahun_berdiri' => 1959,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 01 Rambatan merupakan sekolah unggulan di Kecamatan Rambatan.',
                'visi' => 'Unggul dalam prestasi, berkarakter Pancasila, dan berwawasan global.',
                'misi' => 'Meningkatkan prestasi siswa; Membentuk karakter Pancasila; Mengembangkan wawasan global.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Rambatan',
                'npsn' => '10100015',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Pendidikan No. 6, Rambatan',
                'latitude' => -0.52345678,
                'longitude' => 100.66345678,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Mardiah, S.Pd.',
                'kontak' => '081234567815',
                'tahun_berdiri' => 1978,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 02 Rambatan melayani pendidikan bagi masyarakat di wilayah Rambatan bagian selatan.',
                'visi' => 'Berprestasi, beriman, dan berbudaya.',
                'misi' => 'Meningkatkan kualitas akademik; Membina keimanan siswa; Melestarikan budaya daerah.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Batipuh',
                'npsn' => '10100016',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Batipuh No. 2, Batipuh',
                'latitude' => -0.47000000,
                'longitude' => 100.54000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Nurdin, M.Pd.',
                'kontak' => '081234567816',
                'tahun_berdiri' => 1957,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 01 Batipuh memiliki tradisi akademik yang kuat dan prestasi di bidang olahraga.',
                'visi' => 'Mewujudkan siswa cerdas, sehat, dan berakhlak mulia.',
                'misi' => 'Mengoptimalkan proses pembelajaran; Meningkatkan kesehatan jasmani; Membina akhlak siswa.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Batipuh',
                'npsn' => '10100017',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Datuak Parpatiah No. 15, Batipuh',
                'latitude' => -0.47345678,
                'longitude' => 100.54345678,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Rosnita, S.Pd.',
                'kontak' => '081234567817',
                'tahun_berdiri' => 1980,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 02 Batipuh terus berinovasi dalam pembelajaran untuk meningkatkan mutu pendidikan.',
                'visi' => 'Sekolah berkualitas, siswa berprestasi.',
                'misi' => 'Meningkatkan mutu pembelajaran; Mengembangkan potensi siswa; Membangun kerjasama dengan masyarakat.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Pariangan',
                'npsn' => '10100018',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Pariangan No. 4, Pariangan',
                'latitude' => -0.45000000,
                'longitude' => 100.52000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Amrizal, M.Pd.',
                'kontak' => '081234567818',
                'tahun_berdiri' => 1963,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 01 Pariangan berada di Nagari Pariangan yang terkenal sebagai desa terindah di dunia.',
                'visi' => 'Terwujudnya siswa unggul, berbudaya, dan berwawasan lingkungan.',
                'misi' => 'Meningkatkan prestasi akademik; Melestarikan budaya Minangkabau; Menjaga kelestarian lingkungan.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 02 Pariangan',
                'npsn' => '10100019',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Sutan Alam No. 9, Pariangan',
                'latitude' => -0.45345678,
                'longitude' => 100.52345678,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Deswita, S.Pd.',
                'kontak' => '081234567819',
                'tahun_berdiri' => 1982,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 02 Pariangan melayani pendidikan dasar di wilayah Nagari Pariangan.',
                'visi' => 'Cerdas, kreatif, dan berakhlak mulia.',
                'misi' => 'Menyelenggarakan pendidikan berkualitas; Mengembangkan kreativitas siswa; Membina akhlak karimah.',
            ],
            [
                'nama_sekolah' => 'SD Negeri 01 Salimpaung',
                'npsn' => '10100020',
                'jenjang' => 'SD',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Salimpaung No. 6, Salimpaung',
                'latitude' => -0.43000000,
                'longitude' => 100.55000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Bustami, M.Pd.',
                'kontak' => '081234567820',
                'tahun_berdiri' => 1961,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SD Negeri 01 Salimpaung memiliki program unggulan di bidang seni dan olahraga.',
                'visi' => 'Unggul dalam prestasi, beriman, dan berbudaya.',
                'misi' => 'Meningkatkan prestasi siswa; Membina iman dan taqwa; Mengembangkan seni dan olahraga.',
            ],

            // ==================== SMP (15 data) ====================
            [
                'nama_sekolah' => 'SMP Negeri 1 Batusangkar',
                'npsn' => '20100001',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Pendidikan No. 1, Batusangkar',
                'latitude' => -0.45500000,
                'longitude' => 100.59000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Ali Amran, M.Pd.',
                'kontak' => '081234567821',
                'tahun_berdiri' => 1952,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://smpn1batusangkar.sch.id',
                'deskripsi_sekolah' => 'SMP Negeri 1 Batusangkar merupakan sekolah menengah pertama tertua dan terfavorit di Kabupaten Tanah Datar.',
                'visi' => 'Terwujudnya siswa berprestasi, berkarakter, dan berwawasan global.',
                'misi' => 'Menyelenggarakan pembelajaran bermutu; Membangun karakter siswa; Mengembangkan wawasan global.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 2 Batusangkar',
                'npsn' => '20100002',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Diponegoro No. 20, Batusangkar',
                'latitude' => -0.45800000,
                'longitude' => 100.59300000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Dra. Hj. Nurlela, M.Pd.',
                'kontak' => '081234567822',
                'tahun_berdiri' => 1960,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://smpn2batusangkar.sch.id',
                'deskripsi_sekolah' => 'SMP Negeri 2 Batusangkar dikenal dengan program adiwiyata dan prestasi di bidang lingkungan hidup.',
                'visi' => 'Unggul dalam mutu, berbudaya lingkungan, dan berakhlak mulia.',
                'misi' => 'Meningkatkan mutu akademik; Membudayakan cinta lingkungan; Membina akhlak siswa.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 3 Batusangkar',
                'npsn' => '20100003',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Soekarno Hatta No. 30, Batusangkar',
                'latitude' => -0.46100000,
                'longitude' => 100.59600000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Zulhendri, M.Pd.',
                'kontak' => '081234567823',
                'tahun_berdiri' => 1965,
                'kurikulum' => 'Kurikulum 2013',
                'website' => 'https://smpn3batusangkar.sch.id',
                'deskripsi_sekolah' => 'SMP Negeri 3 Batusangkar memiliki program unggulan tahfidz Al-Quran dan sains.',
                'visi' => 'Mewujudkan generasi cerdas, beriman, dan berdaya saing tinggi.',
                'misi' => 'Mengoptimalkan pembelajaran sains; Membina hafalan Al-Quran; Mengembangkan daya saing siswa.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Sungai Tarab',
                'npsn' => '20100004',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Sungai Tarab No. 15, Sungai Tarab',
                'latitude' => -0.42200000,
                'longitude' => 100.56200000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. Syahrial, M.Pd.',
                'kontak' => '081234567824',
                'tahun_berdiri' => 1963,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Sungai Tarab merupakan sekolah menengah pertama favorit di Kecamatan Sungai Tarab.',
                'visi' => 'Berprestasi, berkarakter, dan berwawasan lingkungan.',
                'misi' => 'Meningkatkan prestasi siswa; Membentuk karakter positif; Menanamkan kepedulian lingkungan.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Lima Kaum',
                'npsn' => '20100005',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Lima Kaum No. 10, Lima Kaum',
                'latitude' => -0.48200000,
                'longitude' => 100.61200000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Maswardi, M.Pd.',
                'kontak' => '081234567825',
                'tahun_berdiri' => 1967,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Lima Kaum memiliki prestasi di bidang akademik dan non-akademik.',
                'visi' => 'Terwujudnya siswa unggul, beriman, dan berbudaya.',
                'misi' => 'Meningkatkan mutu pendidikan; Membina keimanan siswa; Melestarikan budaya daerah.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Tanjung Emas',
                'npsn' => '20100006',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Tanjung Emas No. 8, Tanjung Emas',
                'latitude' => -0.44200000,
                'longitude' => 100.58200000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Arman, M.Pd.',
                'kontak' => '081234567826',
                'tahun_berdiri' => 1970,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Tanjung Emas melayani pendidikan menengah pertama di Kecamatan Tanjung Emas.',
                'visi' => 'Cerdas, kreatif, dan berakhlak mulia.',
                'misi' => 'Menyelenggarakan pembelajaran inovatif; Mengembangkan kreativitas siswa; Membina akhlak karimah.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Padang Ganting',
                'npsn' => '20100007',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Padang Ganting No. 5, Padang Ganting',
                'latitude' => -0.50200000,
                'longitude' => 100.64200000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Drs. H. Zulkarnain, M.Pd.',
                'kontak' => '081234567827',
                'tahun_berdiri' => 1975,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Padang Ganting berkomitmen memberikan pendidikan berkualitas bagi masyarakat.',
                'visi' => 'Berprestasi, beriman, dan berbudaya.',
                'misi' => 'Meningkatkan prestasi akademik; Membina iman dan taqwa; Melestarikan budaya lokal.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Rambatan',
                'npsn' => '20100008',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Rambatan No. 7, Rambatan',
                'latitude' => -0.52200000,
                'longitude' => 100.66200000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Syafril, M.Pd.',
                'kontak' => '081234567828',
                'tahun_berdiri' => 1968,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Rambatan memiliki program unggulan di bidang teknologi informasi.',
                'visi' => 'Unggul dalam prestasi, berbasis teknologi, dan berakhlak mulia.',
                'misi' => 'Mengintegrasikan teknologi dalam pembelajaran; Meningkatkan prestasi siswa; Membina akhlak mulia.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Batipuh',
                'npsn' => '20100009',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Batipuh No. 5, Batipuh',
                'latitude' => -0.47200000,
                'longitude' => 100.54200000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Asril, M.Pd.',
                'kontak' => '081234567829',
                'tahun_berdiri' => 1972,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Batipuh dikenal dengan prestasi di bidang olahraga dan seni.',
                'visi' => 'Cerdas, sehat, dan berakhlak mulia.',
                'misi' => 'Meningkatkan kecerdasan siswa; Mengembangkan olahraga dan seni; Membina akhlak siswa.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Pariangan',
                'npsn' => '20100010',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Pariangan No. 3, Pariangan',
                'latitude' => -0.45200000,
                'longitude' => 100.52200000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Drs. H. Edwar, M.Pd.',
                'kontak' => '081234567830',
                'tahun_berdiri' => 1978,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Pariangan melayani pendidikan di Nagari Pariangan yang bersejarah.',
                'visi' => 'Berprestasi, berbudaya, dan berwawasan lingkungan.',
                'misi' => 'Meningkatkan prestasi siswa; Melestarikan budaya; Menjaga lingkungan.',
            ],
            [
                'nama_sekolah' => 'SMP Negeri 1 Salimpaung',
                'npsn' => '20100011',
                'jenjang' => 'SMP',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Raya Salimpaung No. 8, Salimpaung',
                'latitude' => -0.43200000,
                'longitude' => 100.55200000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Bahar, M.Pd.',
                'kontak' => '081234567831',
                'tahun_berdiri' => 1973,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => null,
                'deskripsi_sekolah' => 'SMP Negeri 1 Salimpaung memiliki program unggulan di bidang sains dan matematika.',
                'visi' => 'Unggul dalam sains, beriman, dan berbudaya.',
                'misi' => 'Mengembangkan pembelajaran sains; Membina iman siswa; Melestarikan budaya.',
            ],
            [
                'nama_sekolah' => 'SMP Swasta Bina Bangsa Batusangkar',
                'npsn' => '20100012',
                'jenjang' => 'SMP',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Pendidikan No. 5, Batusangkar',
                'latitude' => -0.46400000,
                'longitude' => 100.59900000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'H. M. Yasin, S.Pd., M.M.',
                'kontak' => '081234567832',
                'tahun_berdiri' => 1985,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://smpbinabangsa.sch.id',
                'deskripsi_sekolah' => 'SMP Swasta Bina Bangsa merupakan sekolah swasta favorit dengan program bilingual.',
                'visi' => 'Terwujudnya generasi berprestasi, berkarakter Islami, dan berwawasan internasional.',
                'misi' => 'Menyelenggarakan pendidikan bilingual; Membina karakter Islami; Mengembangkan wawasan internasional.',
            ],
            [
                'nama_sekolah' => 'SMP Swasta Muhammadiyah Batusangkar',
                'npsn' => '20100013',
                'jenjang' => 'SMP',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Muhammadiyah No. 2, Batusangkar',
                'latitude' => -0.46700000,
                'longitude' => 100.60200000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Daswir, M.Pd.',
                'kontak' => '081234567833',
                'tahun_berdiri' => 1980,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://smpmuhbatusangkar.sch.id',
                'deskripsi_sekolah' => 'SMP Muhammadiyah Batusangkar menggabungkan pendidikan umum dan keagamaan Islam.',
                'visi' => 'Unggul dalam akademik, berjiwa Islami, dan berakhlak karimah.',
                'misi' => 'Meningkatkan mutu akademik; Membina jiwa Islami; Membentuk akhlak karimah.',
            ],
            [
                'nama_sekolah' => 'SMP Swasta PGRI Batusangkar',
                'npsn' => '20100014',
                'jenjang' => 'SMP',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. PGRI No. 3, Batusangkar',
                'latitude' => -0.47000000,
                'longitude' => 100.60500000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Supriadi, S.Pd., M.Pd.',
                'kontak' => '081234567834',
                'tahun_berdiri' => 1988,
                'kurikulum' => 'Kurikulum 2013',
                'website' => null,
                'deskripsi_sekolah' => 'SMP PGRI Batusangkar berkomitmen mencerdaskan kehidupan bangsa melalui pendidikan berkualitas.',
                'visi' => 'Cerdas, terampil, dan berakhlak mulia.',
                'misi' => 'Meningkatkan kecerdasan siswa; Mengembangkan keterampilan; Membina akhlak mulia.',
            ],
            [
                'nama_sekolah' => 'SMP Swasta Islam Terpadu Al-Azhar Batusangkar',
                'npsn' => '20100015',
                'jenjang' => 'SMP',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Al-Azhar No. 1, Batusangkar',
                'latitude' => -0.47500000,
                'longitude' => 100.60800000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Drs. H. Firdaus, M.Pd.I.',
                'kontak' => '081234567835',
                'tahun_berdiri' => 1995,
                'kurikulum' => 'Kurikulum Merdeka',
                'website' => 'https://smpitazhar.sch.id',
                'deskripsi_sekolah' => 'SMP IT Al-Azhar Batusangkar mengintegrasikan ilmu pengetahuan umum dan agama Islam.',
                'visi' => 'Mewujudkan generasi Islami, cerdas, dan berprestasi.',
                'misi' => 'Mengintegrasikan ilmu umum dan agama; Membina kecerdasan siswa; Meningkatkan prestasi.',
            ],

            // ==================== TK (15 data) ====================
            [
                'nama_sekolah' => 'TK Negeri Pembina Batusangkar',
                'npsn' => '30100001',
                'jenjang' => 'TK',
                'kategori' => 'Negeri',
                'alamat' => 'Jl. Pendidikan No. 2, Batusangkar',
                'latitude' => -0.45400000,
                'longitude' => 100.58800000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Yusnita, S.Pd., M.Pd.',
                'kontak' => '081234567836',
                'tahun_berdiri' => 1985,
                'kurikulum' => 'Kurikulum Merdeka PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Negeri Pembina Batusangkar merupakan TK negeri percontohan di Kabupaten Tanah Datar.',
                'visi' => 'Terwujudnya anak usia dini yang cerdas, kreatif, dan berakhlak mulia.',
                'misi' => 'Menyelenggarakan pembelajaran yang menyenangkan; Mengembangkan kreativitas anak; Membina akhlak sejak dini.',
            ],
            [
                'nama_sekolah' => 'TK Pertiwi Batusangkar',
                'npsn' => '30100002',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Merdeka No. 5, Batusangkar',
                'latitude' => -0.45700000,
                'longitude' => 100.59100000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Ermita, S.Pd.',
                'kontak' => '081234567837',
                'tahun_berdiri' => 1988,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Pertiwi Batusangkar memiliki program belajar sambil bermain yang interaktif.',
                'visi' => 'Anak ceria, cerdas, dan berkarakter.',
                'misi' => 'Menciptakan lingkungan belajar yang aman dan menyenangkan; Mengembangkan potensi anak; Membentuk karakter positif.',
            ],
            [
                'nama_sekolah' => 'TK Aisyiyah Bustanul Athfal Batusangkar',
                'npsn' => '30100003',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Aisyiyah No. 3, Batusangkar',
                'latitude' => -0.46000000,
                'longitude' => 100.59400000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Nurhasanah, S.Pd.I.',
                'kontak' => '081234567838',
                'tahun_berdiri' => 1990,
                'kurikulum' => 'Kurikulum Merdeka PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Aisyiyah Bustanul Athfal mengintegrasikan nilai-nilai Islam dalam pembelajaran.',
                'visi' => 'Membentuk generasi Islami, cerdas, dan mandiri sejak usia dini.',
                'misi' => 'Menanamkan nilai-nilai Islam; Mengembangkan kecerdasan anak; Membina kemandirian.',
            ],
            [
                'nama_sekolah' => 'TK Harapan Bunda Batusangkar',
                'npsn' => '30100004',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Diponegoro No. 10, Batusangkar',
                'latitude' => -0.46300000,
                'longitude' => 100.59700000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Rita Yuliana, S.Pd.',
                'kontak' => '081234567839',
                'tahun_berdiri' => 1995,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Harapan Bunda menyediakan pendidikan anak usia dini yang berkualitas.',
                'visi' => 'Anak pintar, kreatif, dan berakhlak baik.',
                'misi' => 'Mengembangkan potensi anak secara optimal; Menumbuhkan kreativitas; Membina akhlak anak.',
            ],
            [
                'nama_sekolah' => 'TK Islam Terpadu Al-Falah Batusangkar',
                'npsn' => '30100005',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Al-Falah No. 2, Batusangkar',
                'latitude' => -0.46600000,
                'longitude' => 100.60000000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Hj. Zulhijjah, S.Pd.I.',
                'kontak' => '081234567840',
                'tahun_berdiri' => 2000,
                'kurikulum' => 'Kurikulum Merdeka PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK IT Al-Falah menggabungkan pendidikan umum dengan hafalan Al-Quran sejak dini.',
                'visi' => 'Mewujudkan generasi Qurani, cerdas, dan berakhlak mulia.',
                'misi' => 'Mengenalkan Al-Quran sejak dini; Mengembangkan kecerdasan anak; Membina akhlak mulia.',
            ],
            [
                'nama_sekolah' => 'TK Pertiwi Sungai Tarab',
                'npsn' => '30100006',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Raya Sungai Tarab No. 5, Sungai Tarab',
                'latitude' => -0.42100000,
                'longitude' => 100.56100000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Mardalena, S.Pd.',
                'kontak' => '081234567841',
                'tahun_berdiri' => 1992,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Pertiwi Sungai Tarab melayani pendidikan anak usia dini di Kecamatan Sungai Tarab.',
                'visi' => 'Anak ceria, mandiri, dan berakhlak mulia.',
                'misi' => 'Menciptakan suasana belajar yang gembira; Membina kemandirian anak; Menanamkan akhlak mulia.',
            ],
            [
                'nama_sekolah' => 'TK Aisyiyah Sungai Tarab',
                'npsn' => '30100007',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Pendidikan No. 1, Sungai Tarab',
                'latitude' => -0.42400000,
                'longitude' => 100.56400000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Yusmaini, S.Pd.I.',
                'kontak' => '081234567842',
                'tahun_berdiri' => 1993,
                'kurikulum' => 'Kurikulum Merdeka PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Aisyiyah Sungai Tarab memberikan pendidikan berbasis Islam untuk anak usia dini.',
                'visi' => 'Membentuk anak sholeh/sholehah, cerdas, dan mandiri.',
                'misi' => 'Menanamkan nilai keislaman; Mengembangkan kecerdasan; Membina kemandirian.',
            ],
            [
                'nama_sekolah' => 'TK Pertiwi Lima Kaum',
                'npsn' => '30100008',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Raya Lima Kaum No. 3, Lima Kaum',
                'latitude' => -0.48100000,
                'longitude' => 100.61100000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Eli Marlina, S.Pd.',
                'kontak' => '081234567843',
                'tahun_berdiri' => 1994,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Pertiwi Lima Kaum melayani pendidikan anak usia dini di Kecamatan Lima Kaum.',
                'visi' => 'Anak cerdas, kreatif, dan berkarakter.',
                'misi' => 'Mengembangkan potensi anak; Menumbuhkan kreativitas; Membentuk karakter positif.',
            ],
            [
                'nama_sekolah' => 'TK Aisyiyah Lima Kaum',
                'npsn' => '30100009',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Datuak Bandaro No. 5, Lima Kaum',
                'latitude' => -0.48400000,
                'longitude' => 100.61400000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Nurhayati, S.Pd.I.',
                'kontak' => '081234567844',
                'tahun_berdiri' => 1996,
                'kurikulum' => 'Kurikulum Merdeka PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Aisyiyah Lima Kaum mengintegrasikan pendidikan Islam dalam kegiatan belajar.',
                'visi' => 'Generasi Islami, cerdas, dan mandiri.',
                'misi' => 'Menanamkan nilai Islam; Mengembangkan kecerdasan; Membina kemandirian anak.',
            ],
            [
                'nama_sekolah' => 'TK Pertiwi Tanjung Emas',
                'npsn' => '30100010',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Tanjung Emas No. 2, Tanjung Emas',
                'latitude' => -0.44100000,
                'longitude' => 100.58100000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Desi Armita, S.Pd.',
                'kontak' => '081234567845',
                'tahun_berdiri' => 1997,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Pertiwi Tanjung Emas menyediakan pendidikan anak usia dini yang berkualitas.',
                'visi' => 'Anak pintar, ceria, dan berakhlak baik.',
                'misi' => 'Mengoptimalkan tumbuh kembang anak; Menciptakan pembelajaran menyenangkan; Membina akhlak.',
            ],
            [
                'nama_sekolah' => 'TK Aisyiyah Tanjung Emas',
                'npsn' => '30100011',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. M. Yamin No. 5, Tanjung Emas',
                'latitude' => -0.44400000,
                'longitude' => 100.58400000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Zulhijjah, S.Pd.I.',
                'kontak' => '081234567846',
                'tahun_berdiri' => 1998,
                'kurikulum' => 'Kurikulum Merdeka PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Aisyiyah Tanjung Emas memberikan pendidikan anak usia dini berbasis Islam.',
                'visi' => 'Mewujudkan anak sholeh/sholehah, cerdas, dan mandiri.',
                'misi' => 'Membina keimanan anak; Mengembangkan kecerdasan; Membentuk kemandirian.',
            ],
            [
                'nama_sekolah' => 'TK Pertiwi Rambatan',
                'npsn' => '30100012',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Raya Rambatan No. 2, Rambatan',
                'latitude' => -0.52100000,
                'longitude' => 100.66100000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Yulnetti, S.Pd.',
                'kontak' => '081234567847',
                'tahun_berdiri' => 1995,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Pertiwi Rambatan melayani pendidikan anak usia dini di Kecamatan Rambatan.',
                'visi' => 'Anak ceria, cerdas, dan berkarakter.',
                'misi' => 'Menyediakan lingkungan belajar yang aman; Mengembangkan potensi anak; Membentuk karakter.',
            ],
            [
                'nama_sekolah' => 'TK Aisyiyah Batipuh',
                'npsn' => '30100013',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Raya Batipuh No. 1, Batipuh',
                'latitude' => -0.47100000,
                'longitude' => 100.54100000,
                'akreditasi' => 'A',
                'kepala_sekolah' => 'Rosmawati, S.Pd.I.',
                'kontak' => '081234567848',
                'tahun_berdiri' => 1996,
                'kurikulum' => 'Kurikulum Merdeka PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Aisyiyah Batipuh memberikan pendidikan anak usia dini dengan nuansa Islami.',
                'visi' => 'Anak Islami, cerdas, dan mandiri.',
                'misi' => 'Menanamkan nilai keislaman; Mengembangkan kecerdasan; Membina kemandirian.',
            ],
            [
                'nama_sekolah' => 'TK Pertiwi Pariangan',
                'npsn' => '30100014',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Raya Pariangan No. 1, Pariangan',
                'latitude' => -0.45100000,
                'longitude' => 100.52100000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Eli Zarnis, S.Pd.',
                'kontak' => '081234567849',
                'tahun_berdiri' => 1997,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Pertiwi Pariangan melayani pendidikan anak usia dini di Nagari Pariangan.',
                'visi' => 'Anak cerdas, kreatif, dan berbudaya.',
                'misi' => 'Mengembangkan potensi anak; Menumbuhkan kreativitas; Melestarikan budaya lokal.',
            ],
            [
                'nama_sekolah' => 'TK Pertiwi Salimpaung',
                'npsn' => '30100015',
                'jenjang' => 'TK',
                'kategori' => 'Swasta',
                'alamat' => 'Jl. Raya Salimpaung No. 2, Salimpaung',
                'latitude' => -0.43100000,
                'longitude' => 100.55100000,
                'akreditasi' => 'B',
                'kepala_sekolah' => 'Mardiah, S.Pd.',
                'kontak' => '081234567850',
                'tahun_berdiri' => 1998,
                'kurikulum' => 'Kurikulum 2013 PAUD',
                'website' => null,
                'deskripsi_sekolah' => 'TK Pertiwi Salimpaung menyediakan pendidikan anak usia dini di Kecamatan Salimpaung.',
                'visi' => 'Anak ceria, mandiri, dan berakhlak mulia.',
                'misi' => 'Menciptakan pembelajaran yang menyenangkan; Membina kemandirian; Menanamkan akhlak mulia.',
            ],
        ];

        // Insert data menggunakan Query Builder
        $this->db->table('sekolah')->insertBatch($sekolah);

        echo "Seeder Sekolah: 50 data berhasil ditambahkan!\n";
        echo "Detail:\n";
        echo "  - SD  : 20 sekolah\n";
        echo "  - SMP : 15 sekolah\n";
        echo "  - TK  : 15 sekolah\n";
    }
}
